// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPsc9lSTMiRIHYF1c4bXbE-qN400wt9O0',
    appId: '1:619838476690:web:99da7aa76709a5cee0f14b',
    messagingSenderId: '619838476690',
    projectId: 'airlines-app-d128b',
    authDomain: 'airlines-app-d128b.firebaseapp.com',
    storageBucket: 'airlines-app-d128b.appspot.com',
    measurementId: 'G-FVSHSG6K0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv9sHyTgN-1wU-OIa64sQZqbQ7AFNFVbI',
    appId: '1:619838476690:android:850c23c54ea374b2e0f14b',
    messagingSenderId: '619838476690',
    projectId: 'airlines-app-d128b',
    storageBucket: 'airlines-app-d128b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXgXWMg6SdzrjqH-gz_dIK5peHiUBRo_U',
    appId: '1:619838476690:ios:d004ae292da0e6aae0f14b',
    messagingSenderId: '619838476690',
    projectId: 'airlines-app-d128b',
    storageBucket: 'airlines-app-d128b.appspot.com',
    iosClientId: '619838476690-hjetdobt35rb7h4voqcthoiqig40skk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.airlinesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXgXWMg6SdzrjqH-gz_dIK5peHiUBRo_U',
    appId: '1:619838476690:ios:a4222ac1ffc4c6eee0f14b',
    messagingSenderId: '619838476690',
    projectId: 'airlines-app-d128b',
    storageBucket: 'airlines-app-d128b.appspot.com',
    iosClientId: '619838476690-0sihiuqu23btr4m247amej8qvgcsl54b.apps.googleusercontent.com',
    iosBundleId: 'com.example.airlinesApp.RunnerTests',
  );
}
